ruby_version: 2.7.0
fix: true
parallel: true
ignore:
  - test/**/*
  - examples/**/*
  - myapp/**/*
  - 'lib/sidekiq.rb':
    - Lint/InheritException
  - 'lib/**/*':
    - Lint/RescueException
    - Security/YAMLLoad
    - Style/GlobalVars
