language: ruby
sudo: false
cache: bundler
services:
  - redis-server
gemfile:
  - gemfiles/rails_5.gemfile
bundler_args: --without development load_test
rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.0
  - jruby-9.1.17.0
